#!/bin/bash
## @author : Djob Mvondo
## @goal : The goal of this script is to periodically maintain a snapshot of the xen disagregated modules 
## XENSTORE, DOMNET, STORDOM, TOOLDOM, then when one of these modules crashes, restore them to their last
## snapshot configuration state 

. /etc/xen/scripts/hotplugpath.sh


# SNAPSHOT_PERIOD 
## The period in seconds where we take a snapshot of the differents modules and backit up 
## Default : 3600 (one hour)

SNAPSHOT_PERIOD = 3600

# SNAPSHOT_FOLDER 
## The directory where the snapshot images should be saved  
## Default : @XEN_SCRIPT_DIR@/snapshot 

SNAPSHOT_FOLDER = /etc/xen/scripts/snapshot 

# CONFIG_FOLDER
## The folder/directory where the config files 
## are stored, in case we need them to start the modules.
## Default : /etc/xen
CONFIG_FOLDER = /etc/xen 

CMD = ${sbindir}/xl


snap_dom(domname){

    # Test if the snaphsot folder exists 
    if [ ! -d "$SNAPSHOT_FOLDER" ]; then 
        # If not present, create the folder 
        echo "No snapshot folder found"
        echo "Creating snapshot folder"
        mkdir $SNAPSHOT_FOLDER 
    fi 

    # Else we can continue 

    echo "Saving $domname to $SNAPHSOT_FOLDER "
    
    # Get domain id 

    domain_id = $CMD list | grep $domname | awk '{print $2}'

    if [ -f "$SNAPHSOT_FOLDER/$domname.snapshot" ]; then 
        rm $SNAPHSOT_FOLDER/$domname.snapshot
    fi 

    $CMD save -c $domain_id $SNAPHSOT_FOLDER/$domname.snapshot & > /dev/null 
    
}



all_scan(){

    disaggregated_modules = ('Xenstore','domnet','blkdom','tooldom')

    for module in "${disaggregated_modules[@]}"; do 
        
    # Save each module state in the snapshot folder 

    snap_dom($module)

    done

}

# Program a cron tab for all_scan 

while true; do 

    sleep $SNAPSHOT_PERIOD
    
    all_scan()

done 

## crontab -e 
## Add the following line to the crontab 
## 0 * * * * /etc/xen/scripts/periodic-module-save.in
## This will schedule the script each hour 
## Or leave the current implementation of periodic-module-save-in 



